# Generated by Django 3.2.16 on 2023-02-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230210_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
