# Generated by Django 3.2.16 on 2023-02-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20230210_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='worker',
            new_name='employee',
        ),
    ]
