# Generated by Django 3.2.16 on 2023-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_todo_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.ServiceUser'),
        ),
    ]
