# Generated by Django 3.2.16 on 2023-02-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20230214_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
    ]
